#!/usr/bin/env bash

set -o pipefail
set -o nounset
set -o errexit

function perform_task() {
  if which lolcat > /dev/null 2>&1 && which cowsay > /dev/null 2>&1;
  then
    echo "››› $@" | cowsay | lolcat
    sh -c "$@"
  else
    echo "››› brew update"
    brew update
    echo
    echo
  fi
}


cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
perform_task 'brew update'

perform_task 'brew upgrade'

perform_task 'brew bundle'

perform_task 'brew update'

perform_task 'brew upgrade'

perform_task 'brew cleanup --prune-prefix'

if [[ "$(uname)" == "Darwin" ]];
then
  perform_task '$DOTFILES/macos/set-defaults.sh'
fi

#echo "››› files to run during installation: \n$(find $DOTFILES -iname "install.sh")"
#for file in $(find $DOTFILES -iname "install.sh"); do
#  if [[ "$file" == "$DOTFILES/homebrew/install" ]]; then
#    continue
#  fi
#  if echo "$file" | grep -E -i 'python/pyenv' > /dev/null
#  then
#    continue
#  fi

#  echo ""
#  echo "#############################################"
#  echo "Executing file: $file ---->"
#  echo "#############################################"
#  echo ""

#  sh -c $file

#  echo ""
#  echo "<---- Done executing file: $file"
#  echo "---------------------------------------------"
#done

if [[ "$(uname)" == "Linux" ]]; then
  perform_task 'sudo apt update -y'
  sleep 1
  perform_task 'sudo apt upgrade -y'
  sleep 1
  perform_task 'sudo apt autoremove -y'
  sleep 1
fi
