#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
export DOTFILES_ROOT=$(pwd -P)

source $DOTFILES_ROOT/script/linker_source

setup_gitconfig

install_dotfiles

echo ''
echo '  All symlinks installed!'
